version: "3.8"

services:
  backend:
    build: ./backend
    container_name: secret-sniper-backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend/secrets.db:/app/secrets.db
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
